apiVersion: apps/v1
kind: Deployment
metadata:
  name: authzen-api
  labels:
    app: authzen-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: authzen-api
  template:
    metadata:
      labels:
        app: authzen-api
    spec:
      containers:
      - name: authzen-api
        image: authzen-api:latest
        # image: ${DOCKERHUB_USERNAME}/authzen-api:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: "500m"
            memory: "256Mi"
          requests:
            cpu: "100m"
            memory: "128Mi"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
